# Generated by Django 3.2.4 on 2021-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0002_data_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='adjclose',
            field=models.IntegerField(verbose_name='Adj Close'),
        ),
    ]
