# Generated by Django 3.2.4 on 2021-06-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0003_alter_data_adjclose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='adjclose',
            field=models.FloatField(verbose_name='Adj Close'),
        ),
    ]
